### ISSUE TITLE
command 在群聊内不生效

### ISSUE THREAD

**Issue by linonetwo** [zhinjs/zhin#10]
```
  ctx.command('cn <keyword:text>').action(({ options }) => {
    console.log('options', options);
    return 'hello world';
  });
```

```
[2023-02-27T00:15:47.438] [INFO] [zhin] - 已重载插件:tw-qa
[2023-02-27T00:16:11.610] [INFO] [Watch:1287688945] - 更新了群列表，新增了群：[2023-02-27T00:16:17.202] [INFO] [Watch:1287688945] - recv from: [Group: ), Member: 林一二()] {at:} cn test
```

**Comment by linonetwo** [comment]
中间件里能看到

是 command 中间件被截胡了吗？别的中间件没有调 next？

```
    ctx.middleware(async (event,next)=>{
      // DEBUG: console event
      console.log(`event`, event);
        if(true){ //需要判断的条件
        //逻辑执行代码
        }else{
            next() // 不next，则不会流入下一个中间件
        }
    });
```

但目前没别的插件

```
plugins:
  watcher: /Users/linonetwo/Desktop/repo/qq-bot
  tw-qa: null
```

**Comment by lc-cn** [comment]
被你自己定义的中间件截胡了

**Comment by linonetwo** [comment]
没有，仅加

```
 ctx.command('cn <keyword:text>').action(({ options }) => {
    console.log('options', options);
    return 'hello world';
  });
```

也收不到，我是加了个中间件 debug 看框架有没有收到消息

**Comment by linonetwo** [comment]
这样也不行

```
import { Plugin, Context } from 'zhin';
export const name = 'tw-qa';
export function install(this: Plugin, ctx: Context) {
  // 在这儿实现你的插件逻辑
  // 功能样例：
  //1.定义指令

  ctx.command('cn <keyword:text>').action(({ options }) => {
    console.log('options', options);
    return 'hello world';
  });

  // 2.定义中间件
  
    ctx.middleware(async (event,next)=>{
      // DEBUG: console event
      console.log(`event`, event);
        if(false){ //需要判断的条件
        //逻辑执行代码
        }else{
            next() // 不next，则不会流入下一个中间件
        }
    });
   
  // 3. 监听事件
  /*
    ctx.on(eventName,callback);
    ctx.once(eventName,callback);
    ctx.on(eventName,callback);
    */
  // 4. 定义服务
  /*
    ctx.service('serviceName'，{}) // 往bot上添加可全局访问的属性
    */
  // 5. 添加自定插件副作用(在插件卸载时需要执行的代码)
  // 如果不需要，可以不return
  /*
    return ()=>{
        // 如果你使用过react的useEffect 那你应该知道这是在干嘛
        // 函数内容将会在插件卸载时自动卸载
    }
    */
}

```

```
[2023-03-03T14:19:16.718] [MARK] [Watch:1287688945] - 加载了4个好友，1个群，0个频道，0个陌生人
[2023-03-03T14:20:56.310] [INFO] [Watch:1287688945] - recv from: [Group: , Member: ] {at:} cn test
```

**Comment by lc-cn** [comment]
> 这样也不行
> 
> ```
> import { Plugin, Context } from 'zhin';
> export const name = 'tw-qa';
> export function install(this: Plugin, ctx: Context) {
>   // 在这儿实现你的插件逻辑
>   // 功能样例：
>   //1.定义指令
> 
>   ctx.command('cn <keyword:text>').action(({ options }) => {
>     console.log('options', options);
>     return 'hello world';
>   });
> 
>   // 2.定义中间件
>   
>     ctx.middleware(async (event,next)=>{
>       // DEBUG: console event
>       console.log(`event`, event);
>         if(false){ //需要判断的条件
>         //逻辑执行代码
>         }else{
>             next() // 不next，则不会流入下一个中间件
>         }
>     });
>    
>   // 3. 监听事件
>   /*
>     ctx.on(eventName,callback);
>     ctx.once(eventName,callback);
>     ctx.on(eventName,callback);
>     */
>   // 4. 定义服务
>   /*
>     ctx.service('serviceName'，{}) // 往bot上添加可全局访问的属性
>     */
>   // 5. 添加自定插件副作用(在插件卸载时需要执行的代码)
>   // 如果不需要，可以不return
>   /*
>     return ()=>{
>         // 如果你使用过react的useEffect 那你应该知道这是在干嘛
>         // 函数内容将会在插件卸载时自动卸载
>     }
>     */
> }
> ```
> 
> ```
> [2023-03-03T14:19:16.718] [MARK] [Watch:1287688945] - 加载了4个好友，1个群，0个频道，0个陌生人
> [2023-03-03T14:20:56.310] [INFO] [Watch:1287688945] - recv from: [Group: , Member: ] {at:} cn test
> ```

输入格式错误，未匹配指令

**Comment by linonetwo** [comment]
`cn <keyword:text>` 应该会匹配 `cn test` 吧

**Comment by linonetwo** [comment]
真实原因：这款机器人不支持 @机器人名 ，不然无法识别指令。

只能直接在群里说 cn test

**Comment by linonetwo** [comment]
这和别的机器人框架不大一样，希望文档能说明一下
