### ISSUE TITLE
[求助] win11 下安装出现的包括但不限于命令缺失的问题

### ISSUE THREAD

**Issue by caibyte** [zhinjs/zhin#113]
可能是系统的原因，也可能是我傻逼了。

- 尝试直接使用 `npm init zhin`，输完项目名称后报错 `AxiosError: connect ECONNREFUSED 127.0.0.1:443`，看了看信息应该本来是要请求 <https://github.com/zhinjs/boilerplate/archive/refs/heads/master.tar.gz>，不知道为什么飘到本地来了。
- 尝试安装 cli，直到项目创建成功都没有报错。`zhin start` 启动的时候报错 `Error: spawn npm ENOENT`，这个我查了下应该是系统差异。之后直接 `npm run start`，提示没有 `start-zhin` 这个命令。

现在只想找个方法安装一下。

系统 win11，安装均使用默认最新版本。

**Comment by caibyte** [comment]
又试了下 README 上的安装方式：

```
Couldn't find tsconfig.json. tsconfig-paths will be skipped
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader.
On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
```

显然还是系统差异。

**Comment by lc-cn** [comment]
已修复
