### ISSUE TITLE
Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by linonetwo** [zhinjs/zhin#12]
```
TypeError: Cannot read properties of undefined (reading 'toString')
    at generateShortDevice (qq-bot/node_modules/oicq/lib/core/device.js:47:35)
```

```
        wifi_ssid: `TP-LINK-${uin.toString(16)}`,
```

**Comment by lc-cn** [comment]
> ```
> TypeError: Cannot read properties of undefined (reading 'toString')
>     at generateShortDevice (qq-bot/node_modules/oicq/lib/core/device.js:47:35)
> ```
> 
> ```
>         wifi_ssid: `TP-LINK-${uin.toString(16)}`,
> ```

版本过久，
