### ISSUE TITLE
无法找到package.json

### ISSUE THREAD

**Issue by lingdu2333** [zhinjs/zhin#128]
npm仓库中的 /zhin/lib/constants.js 121行中的`exports.version = JSON.parse(fs.readFileSync(path_1.default.resolve('../package.json'), 'utf8')).version;`
多打了一个`. `识别到了前一个目录的package.json 导致无法创建项目
![1a6d9c16696b31d355b8e25d8f7be143](https://github.com/zhinjs/zhin/assets/117048039/3aee20e5-7ad8-4065-ad12-e0a461f7e482)

**Comment by lc-cn** [comment]
已修复，谢谢反馈
