### ISSUE TITLE
type text is not defined

### ISSUE THREAD

**Issue by linonetwo** [zhinjs/zhin#39]
更新了一下就这样了，文档也没写新的用法

**Comment by linonetwo** [comment]
降级回 2.0.7 解决了问题

**Comment by linonetwo** [comment]
我的写法见 https://github.com/tiddly-gittly/qq-bot/blob/master/plugins/tw-qa/src/index.ts

**Comment by lc-cn** [comment]
新版已修复

**Comment by linonetwo** [comment]
2.2.0 还是有这个问题

**Comment by lc-cn** [comment]
使用string替换

**Comment by linonetwo** [comment]
可以，但还报错  option count is required

**Comment by linonetwo** [comment]
文档没看到不 require 的写法

**Comment by lc-cn** [comment]
尖括号代表必填，方括号代表选填
