### ISSUE TITLE
sign_api_addr 未生效

### ISSUE THREAD

**Issue by linonetwo** [zhinjs/zhin#47]
按 https://github.com/icqqjs/icqq/issues/78#issuecomment-1617254310 的建议加了之后，不管是加在 adaptor -> icqq 里，还是直接加在 zhin.yaml 底部，都没生效，还是错误码 45

**Comment by lc-cn** [comment]
[参考[这个comment]](https://github.com/icqqjs/icqq/issues/78#issuecomment-1617517822)
