### ISSUE TITLE
沙盒环境？

### ISSUE THREAD

**Issue by huqzc** [zhinjs/zhin#83]
大佬有没有计划做一个沙盒环境，开发时在沙盒环境模拟对话达到调试目的。
因为调试需要本机登录账号，调试期间肯定不让别人用，频繁切换机器人账号也有点危险emmmm

是不是得开发一个适配器？

**Comment by lc-cn** [comment]
???

**Comment by huqzc** [comment]
不好意思，按错键导致写了个标题就发出来了

**Comment by lc-cn** [comment]
那是不是意味着得写个web

**Comment by Lfhsheng** [comment]
> 大佬有没有计划做一个沙盒环境，开发时在沙盒环境模拟对话达到调试目的。 因为调试需要本机登录账号，调试期间肯定不让别人用，频繁切换机器人账号也有点危险emmmm
> 
> 是不是得开发一个适配器？

我觉得您可以再建一个账户用于测试

**Comment by Lfhsheng** [comment]
> 那是不是意味着得写个web

其实可以看看隔壁nonebot有个控制台适配器（

**Comment by huqzc** [comment]
> 我觉得您可以再建一个账户用于测试
目前的确是这样

看了大家的讨论，感觉目前沙盒环境的需求量并不是很大
替代方案（也就是新建个测试账号）也不麻烦

对比之下开发沙盒环境的性价比并不高
那就先搁置?!

**Comment by lc-cn** [comment]
使用adapter-onebot链接onebots，可以让你避免频繁重启导致的登录失败，在正式上线后，再切回zhin自带的适配器，更方便

**Comment by lc-cn** [comment]
已在施工中

**Comment by lc-cn** [comment]
最新版zhin已支持沙箱模式，须安装adapter-mick适配器，并进行相关配置

**Comment by lc-cn** [comment]
> 最新版zhin已支持沙箱模式，须安装adapter-mick适配器，并进行相关配置

adapter-mock 推荐配置如下
```yaml
adapters:
  mock:
    bots:
      - self_id: mock_bot

**Comment by lc-cn** [comment]
沙盒代码见[zhinjs/plugins](https://github.com/zhinjs/plugins/commit/79686364d4b01a17e762bb3b54213364ecceabc3)

**Comment by huqzc** [comment]
赛高
