### ISSUE TITLE
【插件开发】Javascript-setup 模式报错

### ISSUE THREAD

**Issue by huqzc** [zhinjs/zhin#90]
**Bug 描述**
使用 `Javascript-setup` 模式开发插件
启动项目时，载入该插件报错

**复现步骤**
1. `zhin new test` 新建插件
2. 按照 `Javascript-setup` 方式编写代码，如：
```javascript
// index.js
const { useContext } = require("zhin");
const ctx = useContext();
ctx
  .command('test')
  .action(() => 'success');
```

**实际情况**
启动项目后，在载入插件过程中报错。报错内容如下
```shell
TypeError: Cannot read properties of undefined (reading 'call')
    at Plugin.mount (F:\work\mine\bot\zhin\node_modules\zhin\lib\plugin.js:62:45)
    at installPlugin (F:\work\mine\bot\zhin\node_modules\zhin\lib\context.js:223:20)
    at Proxy.plugin (F:\work\mine\bot\zhin\node_modules\zhin\lib\context.js:229:24)
    at getContext (F:\work\mine\bot\zhin\node_modules\zhin\lib\factory.js:85:14)
    at useContext (F:\work\mine\bot\zhin\node_modules\zhin\lib\factory.js:65:16)
    ...
```

**运行环境:**
 - OS: Windown 10
 - Node版本: 16.16.0
 - Zhin版本：2.4.5

**简单分析**
定位到 `plugin.js` 是如下代码：
```javascript
// 根据指定配置挂载插件
class Plugin {
    // code
    mount(ctx) {
        // code
        const result = this.options.install.call(this, ctx);
        // code
    }
    // code
}
```
也就是插件的 `install` 方法为 `undefined`，导致 `call` 调用失败了。
根据文档，setup 语法不用写 `install` 方法。
但是这里没有 `install` 就会报错。

**问题原因**
经过逐步调试发现，在 `zhin.js` 下的 `getInstalledModules` 方法中
当且仅当插件为 `zhin` 的内置插件时，系统才会标识其为 `setup` 插件，并为其添加一个 `install` 方法。
其他插件均不会被标记为 `setup` 插件，也就是说，需要自己提供 `install` 方法。
这就与 `setup` 的意义相悖了。

**解决办法**
1. 不用 `setup` 方式开发插件
或者
2. 在 `package.json` 中加入字段 `"setup": true` 。

第二种方法并没有在文档种说明，而是通过源代码得出来的。建议添加到文档或修改该部分代码逻辑。

**建议**
> 这个建议没有考虑更多因素，如果原方式有其他方面的考量，希望可以告知下~

既然纵使是 `setup` 插件，也是由系统为其添加 `install` 方法
那干脆不用标识是否为 `setup` 方式
而是在加载插件时，判断其是否有 `install` 方法
如果有，不管
如果没有，系统自动为其添加（空的） `install` 方法
这样，无论如何，插件都会有 `install` 方法，也就不会报该错了。

**Comment by lc-cn** [comment]
你的建议无法接受，因为判断是否有install方法需要import，而setup的install就是import包，如果这么判断，属于提前install插件，会报错。
setup目前仅在试验阶段，未写入文档，候选会将package.json中声明setup写入文档

**Comment by huqzc** [comment]
了解了，感谢回复。

另外看到zhin发布了3.0版本，不过在安装过程发现@icqqjs/icqq无法安装
@zhinjs/icqq 也是引用了 @icqqjs/icqq 
貌似相关库被删除了
大佬有什么说法吗

**Comment by huqzc** [comment]
好吧没事了，已经看到icqq转为私有了
